{{ if not .Values.api_key }}
  {{ fail "API key for NASA is required. Can be set via '--set api_key=XXX'" }}
{{ end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nasa-images.fullname" . }}
  labels:
    {{- include "nasa-images.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "nasa-images.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nasa-images.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            {{ if .Values.healthChecks.enabled }}
            - name: health
              containerPort: {{ .Values.healthChecks.port }}
              protocol: TCP
            {{ end }}
          livenessProbe:
            httpGet:
              path: /
              port: health
          readinessProbe:
            httpGet:
              path: /
              port: health
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: API_KEY
              value: {{ .Values.api_key }}
