apiVersion: v1
kind: Service
metadata:
  name: {{ include "nasa-images.fullname" . }}-svc
  labels:
    {{- include "nasa-images.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nasa-images.selectorLabels" . | nindent 4 }}
